# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

# Define services
services:

  # Client Service
  client:
    build:
      context: ./client # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - server
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - devim_case
    restart: unless-stopped

  # Server Service
  server:
    build:
      context: ./server # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "801:8001" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    depends_on:
      - rabbitmq
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - devim_case
    restart: unless-stopped

  # Redis Service
  rabbitmq:
    image: "rabbitmq:alpine" # Use a public RabbitMQ image to build the RabbitMQ service
    restart: unless-stopped
    networks:
      - backend

networks:
  devim_case: