// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DivisionTask struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DivisionTask) Reset()         { *m = DivisionTask{} }
func (m *DivisionTask) String() string { return proto.CompactTextString(m) }
func (*DivisionTask) ProtoMessage()    {}
func (*DivisionTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *DivisionTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DivisionTask.Unmarshal(m, b)
}
func (m *DivisionTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DivisionTask.Marshal(b, m, deterministic)
}
func (m *DivisionTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DivisionTask.Merge(m, src)
}
func (m *DivisionTask) XXX_Size() int {
	return xxx_messageInfo_DivisionTask.Size(m)
}
func (m *DivisionTask) XXX_DiscardUnknown() {
	xxx_messageInfo_DivisionTask.DiscardUnknown(m)
}

var xxx_messageInfo_DivisionTask proto.InternalMessageInfo

func (m *DivisionTask) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*DivisionTask)(nil), "devim_case.DivisionTask")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 88 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2c, 0xce,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x49, 0x2d, 0xcb, 0xcc, 0x8d, 0x4f, 0x4e,
	0x2c, 0x4e, 0x55, 0x52, 0xe3, 0xe2, 0x71, 0xc9, 0x2c, 0xcb, 0x2c, 0xce, 0xcc, 0xcf, 0x0b, 0x49,
	0x2c, 0xce, 0x16, 0x12, 0xe3, 0x62, 0xcb, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x92, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0d, 0x82, 0xf2, 0x92, 0xd8, 0xc0, 0x5a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0x9f, 0x49, 0xa1, 0x48, 0x00, 0x00, 0x00,
}
